name: Develop

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Discord notification
        env:
          DISCORD_USERNAME: GITHUB
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/1093761496485478532/eAMJT--uoPhXphxIVp2zLukA8cwOHaCxQvdp7a7aiGJQLSBZIdMsgJfDzDWz6YQX3k2C
        uses: Ilshidur/action-discord@master
        with:
          args: "[Develop] 🚀 App has been released! \n\n${{ github.event.head_commit.message }} \n\n\nAPK: https://github.com/Mrkonxyz/discord-notify/actions/runs/${{ github.run_id }}"
          color: "#26de81"
